### ISSUE TITLE
Contact form not sending emails

### ISSUE THREAD

**Issue by grumero** [getgrav/grav-skeleton-twenty-site#1]
Hi. I downloaded the skeleton from here `https://getgrav.org/downloads/skeletons`, which points to this download here:
`https://github.com/getgrav/grav-skeleton-twenty-site/releases/download/1.1.0/grav-skeleton-twenty-site-v1.1.0.zip`
Afterwards I installed the admin plugin and updated all plugins.

I can not get the contact form to work and send emails with SMTP. I always get the error message: `Oops there was a problem,...`
My mail settings are definitely correct and proven to work with other grav skeletons .
After a few hours of fiddeling around, checking the form config e.g. I still can't figure out where the problem is.
Could you please download the skeleton from the given link and check this out?
I would be more than happy if I'd get this to work.

Thank You!!

**Comment by flaviocopes** [comment]
I think I fixed this in the theme, but I didn't make a new release.

Update the theme files with the repository files (download from here: https://github.com/getgrav/grav-theme-twenty) and put them under user/themes/. Does it work now?

**Comment by grumero** [comment]
Works like charm now!! Thanks so much!
Just for the learning curve: Where would I have to look at to fix this?

**Comment by flaviocopes** [comment]
I know this because I already looked at this problem.

"Oops there was a problem" happens when the form cannot be sent because it lacks a nonce, something that tells Grav the form submission is legit.

The theme has a custom form twig, to customize the form HTML, and it was built before we added nonces, so it was missing them.
