### ISSUE TITLE
help about how create custom form processing

### ISSUE THREAD

**Issue by cocodrino** [getgrav/grav-skeleton-twenty-site#2]
Hi guys, sorry but I'm a bit stuck about how create custom processing for my forms, right now I'm trying to incorporate the livedrive api so it can send a form response.

I add the form in the modular

```mkd

---
title: myproject
menu: Home
onpage_menu: true
body_class: index
header_class: alt
content:
    items: @self.modular
    order:
        by: default
        dir: asc
        custom:
            - _banner
            - _icons
            - _header
            - _features
            - _portfolio
            - _contact

form:
    name: contacto
    fields:
    -
        name: nombre
        label: Nombre
        placeholder: 'Ingrese ambos nombres'
        autofocus: 'on'
        autocomplete: 'on'
        type: text
        
    -
        name: apellido
        label: Apellido
        type: text
        
    -
        name: correo
        label: Correo Electrónico
        type: email
        validate:
            required : true
        
    - 
      name: telefono
      label: Telefono
      placeholder: 212-222-2222
      type: text
    
    buttons:
    -
        type : submit
        value : Enviar
    

---




```

this forms looks great in my frontpage, now I need add the custom handler for the event, here is where I'm not totally sure about how achieve this...

In the first example in the documentation [here](https://learn.getgrav.org/forms/forms/reference-form-actions#add-your-own-custom-processing-to-a-form) they add the custom handler inside EmailPlugin, but in [this part](https://learn.getgrav.org/forms/forms/reference-form-actions#an-example-of-custom-form-handling) the explanation seems a bit more complicate:

1. Says than I don't need define buttons in my form because templates/login includes them...but if I miss define the button parameter my form render without send button

2) the task would be in my case **myproject.contacto** right?...and I don't need define the action...or do I need?

3) when the user submit the form...must it call **onTask.myproject.contacto**  ??...where must I register this event?....

sorry if these are so much noob question but I was not able to full understand the documentation here
I've [this repo](https://github.com/cocodrino/samplegravform) so you can check if need more details...I'd appreciate if you can guide me about how can I add some custom processing after send the form...

thank you so much

**Comment by flaviocopes** [comment]
Add a `process` to the form definition, like in this example https://learn.getgrav.org/forms/forms/example-form#setup-the-page, like this:

```
process:
    - myaction:
```

then in your plugin, handle the `myaction` as explained in https://learn.getgrav.org/forms/forms/reference-form-actions#add-your-own-custom-processing-to-a-form

**Comment by cocodrino** [comment]
Hi @flaviocopes thanks for the response, just 2 more questions...

1) I can define the myaction handler inside for instance the form.php (/plugin/form.php)

``` php
// /user/plugin/form.php

    public static function getSubscribedEvents()
    {
        return [
            'onPluginsInitialized'   => ['onPluginsInitialized', 0],
            'onTwigTemplatePaths'    => ['onTwigTemplatePaths', 0],
            'myaction' => ['myactionHandler',0]
        ];
    }

    public function myactionHandler($ev){
        dump($ev);
    }


```

2) do I need define an action in my form?..if I'm including the form in the home page (site.com) what could be the action here?

thank you so much for take the time in solve my questions...I'm a bit noob with it right now...thank you!!!

**Comment by flaviocopes** [comment]
As explained in https://learn.getgrav.org/forms/forms/reference-form-actions#add-your-own-custom-processing-to-a-form you need to listen for the `onFormProcessed` event, and in the handler of that event manage the case of "myaction". 

Like the `onFormProcessed` event in the Login plugin, for example: https://github.com/getgrav/grav-plugin-login/blob/develop/login.php

**Comment by cocodrino** [comment]
mm...ok...now it's much more clear, so let me be sure: I can write my custom code inside the LoginPlugin>onFormProcessed (could be also inside FormPlugin?) checking first than the $event['action'] is 'myaction'...is it right no?..

Don't I need define an action parameter inside the form in my modular markdown?...

**Comment by cocodrino** [comment]
@flaviocopes  ok..maybe I'm not so smart for use grav cms :disappointed:  ....

**Comment by flaviocopes** [comment]
Sorry, I missed your last reply until now. You could put that `onFormProcessed` event listener inside any plugin, or even inside your theme. In that event, you can listen for any specific action parameter, _like_ it's done in the Login plugin, that was an example.
