### ISSUE TITLE
Contact page produces error

### ISSUE THREAD

**Issue by awrog** [getgrav/grav-skeleton-twenty-site#5]
https://demo.getgrav.org/twenty-skeleton/contact

generates

Server Error
Sorry, something went terribly wrong!

400 - Template "forms/default/field.html.twig" is not defined in "forms/field.html.twig" at line 1.

**Comment by flaviocopes** [comment]
Thanks for reporting, seems the Form plugin is not installed in the demo, even though it should be. The downloadable skeleton works correctly.
